version: 2
jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: yarn install

      - run: yarn cy:verify

      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.cache

      - run: yarn build

      - run:
          command: yarn dev
          background: true

      - run: yarn e2e

workflows:
  version: 2
  build:
    jobs:
      - test
